steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/myveritext-cto-web:${SHORT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/myveritext-cto-web:${SHORT_SHA}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - myveritext-cto-web
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/myveritext-cto-web:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --no-allow-unauthenticated
      - --port=8080

substitutions:
  _REGION: us-central1
  _REPO: myveritext

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/myveritext-cto-web:${SHORT_SHA}'
