steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/myveritext-cto-web:${_TAG}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/myveritext-cto-web:${_TAG}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - myveritext-cto-web
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/myveritext-cto-web:${_TAG}
      - --region=${_REGION}
      - --platform=managed
      - --no-allow-unauthenticated
      - --port=8080
      - --set-env-vars=PRISMA_CLIENT_ENGINE_TYPE=binary

substitutions:
  _REGION: us-central1
  _REPO: myveritext
  _TAG: latest

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/myveritext-cto-web:${_TAG}'
